---
name: Build and Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set Up Container Structure Test
        id: setup_container_structure_test
        uses: ministryofjustice/modernisation-platform-github-actions/setup-container-structure-test@d682f41c6f6b8c6bc0e06ae38ef41a464aa8a204 # v6.1.6

      - name: Build and Test
        id: build_and_test
        shell: bash
        run: |
          make test
